// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package auth

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/Yahya-Elamri/signeitfaster/views/components"
)

func Login() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = components.Header("/assets/imgs/logoblack.png").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container mx-auto flex items-center justify-center gap-5\"><div class=\"flex-col w-[35%] flex justify-center items-start px-5 h-[75vh]\"><h1 class=\"text-3xl poppins-medium h-[10vh] flex items-center underline\">Sign in</h1><form class=\"w-full flex flex-col gap-5 justify-between items-start fade-in\" hx-post=\"/auth-user\" hx-target=\"this\" hx-swap=\"outerHTML\" method=\"POST\"><div class=\"w-full flex flex-col gap-2\"><label class=\"font-semibold\t font-sans\" for=\"username\">Username or Email</label> <input class=\"border border-[#d5e0d5] focus:outline-none hover:shadow-pink-200 hover:shadow-md focus:shadow-pink-200 focus:shadow-md px-[20px] py-[18px] rounded-xl\" type=\"text\" name=\"Username\" id=\"username\" required></div><div class=\"w-full flex flex-col gap-2\"><label class=\"font-semibold\t font-sans\" for=\"password\">Password</label> <input class=\"border border-[#d5e0d5] focus:outline-none hover:shadow-pink-200 hover:shadow-md focus:shadow-pink-200 focus:shadow-md px-[20px] py-[18px] rounded-xl\" type=\"password\" name=\"PasswordHash\" id=\"password\" required></div><div class=\"w-full flex flex-col items-center gap-2\"><button class=\"poppins-regular bg-green-500 px-4 py-[12px] w-full rounded-full text-white hover:bg-green-700\" type=\"submit\">Sign in</button><h1 class=\"text-[#B4A7AF]\">Don't have an account? <a href=\"/signup\" class=\"underline text-black\">Sign up</a></h1></div></form></div></div><style>\r\n        .fade-in {\r\n            animation: fadeIn 0.5s ease-in-out;\r\n        }\r\n\r\n        @keyframes fadeIn {\r\n            from {\r\n                opacity: 0;\r\n                transform: translateY(-10px);\r\n            }\r\n            to {\r\n                opacity: 1;\r\n                transform: translateY(0);\r\n            }\r\n        }\r\n    </style>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
