// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

import (
	"github.com/Yahya-Elamri/signeitfaster/views/icons"
)

func SidePanel() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"w-full flex-shrink-0 w-[272px] z-10 sticky top-[63px] max-h-[93vh] border-r dark:border-[#3F3F3F] px-4 flex flex-col gap-5 bg-[#ffffff] dark:bg-[#0F0F0F] text-black dark:text-white\"><style>\r\n            .sidebar-dropdown-content {\r\n                max-height: 0;\r\n                overflow: hidden;\r\n                transition: max-height 0.4s ease-in-out;\r\n                box-shadow : 0 0 0 0;\r\n            }\r\n\r\n            .sidebar-dropdown-content.show {\r\n                max-height: 700px;\r\n            }\r\n        </style><ul class=\"flex flex-col items-start justify-start w-full mt-5\"><a href=\"/\" class=\"hover:bg-[#f1f1f1] dark:hover:bg-[#060809] rounded-md w-full px-2 py-3\"><li class=\"poppins-regular flex items-center gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Home("25px", "fill-dark dark:fill-white").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Home</li></a> <a href=\"/tendance\" class=\"hover:bg-[#f1f1f1] dark:hover:bg-[#060809] rounded-md w-full px-2 py-3\"><li class=\"poppins-regular flex items-center gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Fire("25px", "fill-black dark:fill-white").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Tendance</li></a> <a href=\"/communautes\" class=\"hover:bg-[#f1f1f1] dark:hover:bg-[#060809] rounded-md w-full px-2 py-3\"><li class=\"poppins-regular flex items-center gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Group("25px", "fill-black dark:fill-white").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Communautés</li></a></ul><ul class=\"\"><li class=\"dropdown relative border-t dark:border-[#3F3F3F]\"><div class=\"block px-2 py-2 cursor-pointer text-gray-800 flex items-center justify-between mt-2\" onclick=\"toggleSidebarDropdown(event, &#39;sidepanel-dropdown&#39;)\"><span class=\"flex poppins-regular items-center gap-2 text-black dark:text-white\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Market("28px", "fill-dark dark:fill-white").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("MarketPlace </span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Arrow("18px", "stroke-black dark:stroke-white").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><ul id=\"sidepanel-dropdown\" class=\"sidebar-dropdown-content bg-white dark:bg-[#0F0F0F] text-black dark:text-white drop-shadow-none mb-2\"><div class=\"flex flex-col gap-1 px-4 drop-shadow-none\"><a href=\"/marketplace\" class=\"hover:bg-[#f1f1f1] dark:hover:bg-[#060809] rounded-md w-full px-2 py-3\"><p class=\"poppins-regular text-md\">Home</p></a> <a href=\"/marketplace/voituresales\" class=\"hover:bg-[#f1f1f1] dark:hover:bg-[#060809] rounded-md w-full px-2 py-3\"><p class=\"poppins-regular text-md\">Voitures à vendre</p></a> <a href=\"/marketplace/voiturelocation\" class=\"hover:bg-[#f1f1f1] dark:hover:bg-[#060809] rounded-md w-full px-2 py-3\"><p class=\"poppins-regular text-md\">Location des voiture</p></a> <a href=\"/marketplace/voitureparts\" class=\"hover:bg-[#f1f1f1] dark:hover:bg-[#060809] rounded-md w-full px-2 py-3\"><p class=\"poppins-regular text-md\">Pièces de voiture</p></a></div></ul></li><li class=\"dropdown relative border-y dark:border-[#3F3F3F]\"><div hx-get=\"/joined-communautes\" hx-target=\"#data-container\" hx-indicator=\"#loading-spinner\" class=\"block px-2 py-2 cursor-pointer text-gray-800 flex items-center justify-between mt-2\" onclick=\"toggleSidebarDropdown(event, &#39;sidepanel-dropdown2&#39;)\"><span class=\"flex poppins-regular items-center gap-2 text-black dark:text-white\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Group("28px", "fill-black dark:fill-white").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("Mes Communautés </span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = icons.Arrow("18px", "stroke-black dark:stroke-white").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div><ul id=\"sidepanel-dropdown2\" class=\"sidebar-dropdown-content bg-white dark:bg-[#0F0F0F] text-black dark:text-white drop-shadow-none mb-2\"><div class=\"flex flex-col gap-1 px-4 drop-shadow-none\"><a href=\"/communautes/creer\" class=\"hover:bg-[#f1f1f1] dark:hover:bg-[#060809] rounded-md w-full px-2 py-3\"><p class=\"poppins-regular text-md\">Créer Communautés</p></a><style>\r\n                            .my-indicator{\r\n                                display:none;\r\n                            }\r\n                            .htmx-request .my-indicator{\r\n                                display:none;\r\n                            }\r\n                            .htmx-request.my-indicator{\r\n                                display:none;\r\n                            }\r\n                        </style><div id=\"data-container\"></div><div class=\"w-full flex items-center justify-center\"><div id=\"loading-spinner\" class=\"htmx-indicator\"><div class=\"spinner animate-spin rounded-full h-5 w-5 border-2 border-blue-500\"></div></div></div></div></ul></li></ul><script>\r\n            function toggleSidebarDropdown(event, dropdownId) {\r\n                event.preventDefault();\r\n                const dropdown = document.getElementById(dropdownId);\r\n\r\n                if (dropdown.classList.contains('show')) {\r\n                    dropdown.classList.remove('show');\r\n                } else {\r\n                    dropdown.classList.add('show');\r\n                }\r\n            }\r\n        </script></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
